"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { isCategory } from "@/lib/categories";
import { loadEntries, type RangeEntries } from "@/lib/day-data";
import { getTz } from "@/lib/tz";
import { isDay } from "@/lib/time";

export type Result = { error?: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// Allow a little clock skew between phone and server.
const FUTURE_SLACK_MS = 2 * 60 * 1000;

function isId(v: unknown): v is string {
  return typeof v === "string" && UUID.test(v);
}

function isInt(v: unknown, min: number, max: number): v is number {
  return typeof v === "number" && Number.isInteger(v) && v >= min && v <= max;
}

function toIso(ms: unknown) {
  if (typeof ms !== "number" || !Number.isFinite(ms)) return null;
  if (ms > Date.now() + FUTURE_SLACK_MS) return null;
  return new Date(ms).toISOString();
}

function cleanNotes(v: unknown) {
  if (typeof v !== "string") return null;
  const t = v.trim().slice(0, 2000);
  return t === "" ? null : t;
}

function done(error?: { message: string } | null): Result {
  if (error) return { error: error.message };
  revalidatePath("/", "layout");
  return {};
}

const FUTURE = { error: "That time is in the future." };

// ---- actions -------------------------------------------------------------
// Each mutation is a single database round trip; ids are generated by the client
// so the optimistic UI and the saved row share the same id.

const COLOR = /^#[0-9a-fA-F]{6}$/;

function cleanName(v: unknown) {
  return typeof v === "string" && v.trim() !== "" ? v.trim().slice(0, 60) : null;
}

/**
 * Creates an action. `endAt: null` starts a live one that runs until you end it;
 * a number stores a finished action with both stamps.
 */
export async function addAction(input: {
  id: string;
  typeId: string;
  name: string;
  category: string;
  color: string;
  at: number;
  endAt: number | null;
  effort?: number | null;
  pain?: number | null;
  notes?: string | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.typeId) || !name || !isCategory(input.category)) {
    return { error: "Unknown action type." };
  }
  const startedAt = toIso(input.at);
  if (!startedAt) return FUTURE;
  let endedAt: string | null = null;
  if (input.endAt !== null) {
    endedAt = toIso(input.endAt);
    if (!endedAt) return FUTURE;
    if (input.endAt < input.at) return { error: "End time is before the start." };
  }
  const effort = input.effort ?? null;
  if (effort !== null && !isInt(effort, 1, 10)) return { error: "Effort is 1–10." };
  const pain = input.pain ?? null;
  if (pain !== null && !isInt(pain, 0, 10)) return { error: "Pain is 0–10." };

  const supabase = await createClient();
  const res = await supabase.from("actions").insert({
    id: input.id,
    type_id: input.typeId,
    name,
    category: input.category,
    color: COLOR.test(input.color) ? input.color : "#2f5d50",
    started_at: startedAt,
    ended_at: endedAt,
    effort,
    pain,
    notes: cleanNotes(input.notes),
  });
  return done(res.error);
}

/**
 * One tap in the timer field: end whatever is running and start the next task,
 * both at the same instant.
 */
export async function switchTask(input: {
  endId: string | null;
  id: string;
  typeId: string;
  name: string;
  category: string;
  color: string;
  at: number;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.typeId) || !name || !isCategory(input.category)) {
    return { error: "Unknown action type." };
  }
  if (input.endId !== null && !isId(input.endId)) return { error: "Unknown action." };
  const at = toIso(input.at);
  if (!at) return FUTURE;

  const supabase = await createClient();
  const [ended, started] = await Promise.all([
    input.endId
      ? supabase.from("actions").update({ ended_at: at }).eq("id", input.endId).lte("started_at", at)
      : Promise.resolve({ error: null }),
    supabase.from("actions").insert({
      id: input.id,
      type_id: input.typeId,
      name,
      category: input.category,
      color: COLOR.test(input.color) ? input.color : "#2f5d50",
      started_at: at,
    }),
  ]);
  return done(ended.error ?? started.error);
}

/** Pain felt during one action (0–10), or null to clear it. */
export async function setActionPain(input: { id: string; pain: number | null }): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  if (input.pain !== null && !isInt(input.pain, 0, 10)) return { error: "Pain is 0–10." };
  const supabase = await createClient();
  return done((await supabase.from("actions").update({ pain: input.pain }).eq("id", input.id)).error);
}

export async function setActionNotes(input: { id: string; notes: string | null }): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  const supabase = await createClient();
  return done((await supabase.from("actions").update({ notes: cleanNotes(input.notes) }).eq("id", input.id)).error);
}

export async function endAction(input: { id: string; at: number }): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  const endedAt = toIso(input.at);
  if (!endedAt) return FUTURE;

  const supabase = await createClient();
  const { data, error } = await supabase
    .from("actions")
    .update({ ended_at: endedAt })
    .eq("id", input.id)
    .lte("started_at", endedAt)
    .select("id");
  if (error) return { error: error.message };
  if (!data?.length) return { error: "End time is before the start." };
  return done();
}

export async function updateAction(input: {
  id: string;
  startedAt: number;
  endedAt: number | null;
  effort: number | null;
  pain?: number | null;
  notes: string | null;
}): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown action." };
  const startedAt = toIso(input.startedAt);
  if (!startedAt) return FUTURE;
  let endedAt: string | null = null;
  if (input.endedAt !== null) {
    endedAt = toIso(input.endedAt);
    if (!endedAt) return FUTURE;
    if (input.endedAt < input.startedAt) return { error: "End time is before the start." };
  }
  if (input.effort !== null && !isInt(input.effort, 1, 10)) return { error: "Effort is 1–10." };
  const pain = input.pain ?? null;
  if (pain !== null && !isInt(pain, 0, 10)) return { error: "Pain is 0–10." };

  const supabase = await createClient();
  const res = await supabase
    .from("actions")
    .update({
      started_at: startedAt,
      ended_at: endedAt,
      effort: input.effort,
      pain,
      notes: cleanNotes(input.notes),
    })
    .eq("id", input.id);
  return done(res.error);
}

export async function deleteAction(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown action." };
  const supabase = await createClient();
  return done((await supabase.from("actions").delete().eq("id", id)).error);
}

// ---- pain ----------------------------------------------------------------

export async function addPainLevel(input: { id: string; level: number; at: number }): Promise<Result> {
  if (!isId(input.id)) return { error: "Bad id." };
  if (!isInt(input.level, 0, 10)) return { error: "Pain level is 0–10." };
  const recordedAt = toIso(input.at);
  if (!recordedAt) return FUTURE;
  const supabase = await createClient();
  const res = await supabase
    .from("pain_levels")
    .insert({ id: input.id, level: input.level, recorded_at: recordedAt });
  return done(res.error);
}

export async function deletePainLevel(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown reading." };
  const supabase = await createClient();
  return done((await supabase.from("pain_levels").delete().eq("id", id)).error);
}

export async function addPainEvent(input: {
  id: string;
  typeId: string;
  name: string;
  color: string;
  at: number;
  intensity: number | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.typeId) || !name) return { error: "Unknown pain type." };
  if (input.intensity !== null && !isInt(input.intensity, 0, 10)) return { error: "Intensity is 0–10." };
  const occurredAt = toIso(input.at);
  if (!occurredAt) return FUTURE;

  const supabase = await createClient();
  const res = await supabase.from("pain_events").insert({
    id: input.id,
    type_id: input.typeId,
    name,
    color: COLOR.test(input.color) ? input.color : "#c23a3a",
    occurred_at: occurredAt,
    intensity: input.intensity,
  });
  return done(res.error);
}

export async function updatePainEvent(input: {
  id: string;
  at: number;
  intensity: number | null;
  notes: string | null;
}): Promise<Result> {
  if (!isId(input.id)) return { error: "Unknown pain event." };
  if (input.intensity !== null && !isInt(input.intensity, 0, 10)) return { error: "Intensity is 0–10." };
  const occurredAt = toIso(input.at);
  if (!occurredAt) return FUTURE;
  const supabase = await createClient();
  const res = await supabase
    .from("pain_events")
    .update({ occurred_at: occurredAt, intensity: input.intensity, notes: cleanNotes(input.notes) })
    .eq("id", input.id);
  return done(res.error);
}

export async function deletePainEvent(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown pain event." };
  const supabase = await createClient();
  return done((await supabase.from("pain_events").delete().eq("id", id)).error);
}

// ---- whole day -----------------------------------------------------------

const DAY_MIN_MS = 22 * 3_600_000;
const DAY_MAX_MS = 26 * 3_600_000;

/** Deletes everything in one local day: actions overlapping it, readings and events. */
export async function clearDay(input: { startMs: number; endMs: number }): Promise<Result> {
  const { startMs, endMs } = input;
  const length = endMs - startMs;
  if (!Number.isFinite(startMs) || length < DAY_MIN_MS || length > DAY_MAX_MS) {
    return { error: "Bad day range." };
  }
  if (startMs > Date.now() + FUTURE_SLACK_MS) return FUTURE;

  const start = new Date(startMs).toISOString();
  const end = new Date(endMs).toISOString();
  const supabase = await createClient();

  const results = await Promise.all([
    supabase.from("actions").delete().lt("started_at", end).or(`ended_at.is.null,ended_at.gt.${start}`),
    supabase.from("pain_levels").delete().gte("recorded_at", start).lt("recorded_at", end),
    supabase.from("pain_events").delete().gte("occurred_at", start).lt("occurred_at", end),
  ]);
  const failed = results.find((r) => r.error)?.error;
  return done(failed);
}

// ---- timer tasks ---------------------------------------------------------

const TASK_COLORS = ["#3f8f6b", "#5b6ee1", "#a0785a", "#6aa84f", "#e69138", "#7f6a93", "#c27c0e", "#2f5d50"];

/**
 * Add or edit an activity on the timer line. The two timers do different jobs:
 * `notifyAfterMin` only raises an alert and the activity keeps running, while
 * `endAfterMin` ends it — handing over to `nextTypeId` when one is set.
 */
export async function saveTimerTask(input: {
  id: string | null;
  name: string;
  emoji: string | null;
  notifyAfterMin: number | null;
  endAfterMin: number | null;
  nextTypeId: string | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!name) return { error: "Give the activity a name." };
  const minutes = input.notifyAfterMin;
  if (minutes !== null && !isInt(minutes, 1, 600)) return { error: "Notify after 1–600 minutes." };
  const endAfter = input.endAfterMin;
  if (endAfter !== null && !isInt(endAfter, 1, 600)) return { error: "End after 1–600 minutes." };
  // Nothing to hand over to when the activity never ends on its own.
  const nextTypeId = endAfter === null ? null : input.nextTypeId;
  if (nextTypeId !== null && !isId(nextTypeId)) return { error: "Unknown follow-on activity." };
  if (nextTypeId !== null && nextTypeId === input.id) return { error: "An activity cannot follow itself." };
  const emoji = typeof input.emoji === "string" && input.emoji.trim() !== "" ? input.emoji.trim().slice(0, 8) : null;

  const supabase = await createClient();
  const row = { name, emoji, limit_min: minutes, end_min: endAfter, next_type_id: nextTypeId, timer: true };
  const { error } = input.id
    ? await supabase.from("action_types").update(row).eq("id", input.id)
    : await supabase.from("action_types").insert({
        ...row,
        category: "other",
        color: TASK_COLORS[Math.abs([...name].reduce((h, c) => h * 31 + c.charCodeAt(0), 7)) % TASK_COLORS.length],
      });
  if (error) {
    return { error: error.code === "23505" ? "You already have an activity with that name." : error.message };
  }
  revalidatePath("/", "layout");
  return {};
}

/** Take an activity off the timer line (it stays in your types and history). */
export async function removeTimerTask(id: string): Promise<Result> {
  if (!isId(id)) return { error: "Unknown activity." };
  const supabase = await createClient();
  return done((await supabase.from("action_types").update({ timer: false }).eq("id", id)).error);
}

// ---- exercises -----------------------------------------------------------

/** Log one exercise on the timeline, with the set details you did. */
export async function logExercise(input: {
  id: string;
  exerciseId: string;
  name: string;
  color: string;
  at: number;
  endAt: number | null;
  sets: number | null;
  reps: number | null;
  weightKg: number | null;
  restSec: number | null;
  effort: number | null;
  pain: number | null;
  notes: string | null;
}): Promise<Result> {
  const name = cleanName(input.name);
  if (!isId(input.id) || !isId(input.exerciseId) || !name) return { error: "Unknown exercise." };
  const startedAt = toIso(input.at);
  if (!startedAt) return FUTURE;
  let endedAt: string | null = null;
  if (input.endAt !== null) {
    endedAt = toIso(input.endAt);
    if (!endedAt) return FUTURE;
    if (input.endAt < input.at) return { error: "End time is before the start." };
  }
  if (input.sets !== null && !isInt(input.sets, 0, 99)) return { error: "Sets is 0–99." };
  if (input.reps !== null && !isInt(input.reps, 0, 999)) return { error: "Reps is 0–999." };
  if (input.restSec !== null && !isInt(input.restSec, 0, 3600)) return { error: "Rest is 0–3600 seconds." };
  if (input.effort !== null && !isInt(input.effort, 1, 10)) return { error: "Effort is 1–10." };
  if (input.pain !== null && !isInt(input.pain, 0, 10)) return { error: "Pain is 0–10." };
  if (input.weightKg !== null && (!Number.isFinite(input.weightKg) || input.weightKg < 0 || input.weightKg > 9999)) {
    return { error: "Weight looks wrong." };
  }

  const supabase = await createClient();
  const res = await supabase.from("actions").insert({
    id: input.id,
    exercise_id: input.exerciseId,
    name,
    category: "exercise",
    color: COLOR.test(input.color) ? input.color : "#2f5d50",
    started_at: startedAt,
    ended_at: endedAt,
    sets: input.sets,
    reps: input.reps,
    weight_kg: input.weightKg,
    rest_sec: input.restSec,
    effort: input.effort,
    pain: input.pain,
    notes: cleanNotes(input.notes),
  });
  return done(res.error);
}

// ---- timeline range ------------------------------------------------------

/** Entries for a stretch of days, for scrolling further back without a reload. */
export async function fetchEntries(input: { fromDay: string; toDay: string }): Promise<
  { data: RangeEntries; error?: undefined } | { data?: undefined; error: string }
> {
  if (!isDay(input.fromDay) || !isDay(input.toDay) || input.fromDay > input.toDay) {
    return { error: "Bad range." };
  }
  try {
    const tz = await getTz();
    return { data: await loadEntries(tz, input.fromDay, input.toDay) };
  } catch (e) {
    return { error: e instanceof Error ? e.message : "Could not load those days." };
  }
}
